[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Harry Knighton", email = "harryknighton01@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = ""}

