name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
    - name: Install dependencies
      run: pdm install
    - name: Run flake8 linting
      run: pdm run flake8 --config setup.cfg src tests
    - name: Run mypy type checking
      run: pdm run mypy --config-file setup.cfg src tests
    - name: Run pytest tests
      run: pdm run pytest --doctest-modules tests
